In [4]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)


In [3]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


## Data Preprocessing
### Preprocessed by ITBIN-2211-0233

Training Image Preprocessing

In [5]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


Validation Image Preprocessing

In [6]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [7]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [8]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[125.5  105.5  104.5 ]
   [131.25 111.25 110.25]
   [129.75 109.75 108.75]
   ...
   [127.5  107.5  108.5 ]
   [122.   102.   103.  ]
   [109.5   89.5   90.5 ]]

  [[122.   102.   101.  ]
   [130.75 110.75 109.75]
   [127.   107.   106.  ]
   ...
   [115.    95.    96.  ]
   [114.    94.    95.  ]
   [121.5  101.5  102.5 ]]

  [[124.5  104.5  103.5 ]
   [121.5  101.5  100.5 ]
   [126.5  106.5  105.5 ]
   ...
   [120.5  100.5  101.5 ]
   [118.75  98.75  99.75]
   [117.5   97.5   98.5 ]]

  ...

  [[167.25 147.25 148.25]
   [172.5  152.5  153.5 ]
   [169.   149.   150.  ]
   ...
   [167.5  147.5  148.5 ]
   [167.75 147.75 148.75]
   [169.25 149.25 150.25]]

  [[168.5  148.5  149.5 ]
   [159.25 139.25 140.25]
   [159.5  139.5  140.5 ]
   ...
   [173.   153.   154.  ]
   [179.25 159.25 160.25]
   [179.5  159.5  160.5 ]]

  [[160.   140.   141.  ]
   [161.25 141.25 142.25]
   [165.75 145.75 146.75]
   ...
   [172.25 152.25 153.25]
   [164.5  144.5  145.5 ]
   [170.75 150.75 15

Building Model

In [9]:

from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from keras.models import Sequential



In [10]:
model = Sequential()

###  To avoid overshooting

1.Choose default learning rate as 0.0001

2.There may be chance of underfitting, so increase the number of neurons

3.Add more convolution layer to extrat more feature from images, there may be some posibility that model unable to capture relevent feature or model is confusing due to lack of feature. so feed with more feature.


## Building convalution Layer
BUILD BY ITBIN-2211-0256

In [11]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu', input_shape=(128, 128, 3)))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [12]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [13]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [14]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [15]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [16]:
model.add(Dropout(0.25)) # To avoid overfitting

In [17]:

model.add(Flatten())



In [18]:
model.add(Dense(units=1500,activation='relu'))

In [19]:
model.add(Dropout(0.4))

In [20]:
#Output layer
model.add(Dense(units=38,activation='softmax'))

Compiling Model

In [21]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 128, 128, 32)      896       
                                                                 
 conv2d_1 (Conv2D)           (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d (MaxPooling2D  (None, 63, 63, 32)       0         
 )                                                               
                                                                 
 conv2d_2 (Conv2D)           (None, 63, 63, 64)        18496     
                                                                 
 conv2d_3 (Conv2D)           (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 30, 30, 64)       0         
 2D)                                                    

## MODEL TRAINING 

### Model Trained by ITBIN-2211-0258


In [25]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 [==============================] - 129s 56ms/step - loss: 1.3859 - accuracy: 0.5919 - val_loss: 0.5611 - val_accuracy: 0.8252
Epoch 2/10
2197/2197 [==============================] - 123s 56ms/step - loss: 0.4595 - accuracy: 0.8532 - val_loss: 0.2573 - val_accuracy: 0.9161
Epoch 3/10
2197/2197 [==============================] - 125s 57ms/step - loss: 0.2731 - accuracy: 0.9126 - val_loss: 0.1944 - val_accuracy: 0.9381
Epoch 4/10
2197/2197 [==============================] - 125s 57ms/step - loss: 0.1961 - accuracy: 0.9360 - val_loss: 0.2106 - val_accuracy: 0.9344
Epoch 5/10
2197/2197 [==============================] - 125s 57ms/step - loss: 0.1375 - accuracy: 0.9541 - val_loss: 0.1724 - val_accuracy: 0.9447
Epoch 6/10
2197/2197 [==============================] - 125s 57ms/step - loss: 0.1065 - accuracy: 0.9646 - val_loss: 0.1581 - val_accuracy: 0.9507
Epoch 7/10
2197/2197 [==============================] - 125s 57ms/step - loss: 0.0909 - accuracy: 0.9699 - val_loss: 0

## Model Saving

### Model Saved by ITBIN-2211-0258

In [26]:
model.save("trained_model.keras")

In [27]:
training_history.history

{'loss': [1.3858829736709595,
  0.4595470726490021,
  0.27305009961128235,
  0.19606265425682068,
  0.13745465874671936,
  0.10650962591171265,
  0.09086771309375763,
  0.07516758888959885,
  0.06629437953233719,
  0.06029153987765312],
 'accuracy': [0.5918912887573242,
  0.8532185554504395,
  0.9125684499740601,
  0.9360267519950867,
  0.9541361331939697,
  0.9645636081695557,
  0.9699409604072571,
  0.97584468126297,
  0.9790454506874084,
  0.9804680347442627],
 'val_loss': [0.5611236691474915,
  0.2573181092739105,
  0.19435124099254608,
  0.21061702072620392,
  0.17238374054431915,
  0.15811096131801605,
  0.13565747439861298,
  0.1719799041748047,
  0.13282211124897003,
  0.14128470420837402],
 'val_accuracy': [0.8252333402633667,
  0.9160596132278442,
  0.9381402134895325,
  0.9343842267990112,
  0.9446847438812256,
  0.9506601691246033,
  0.9586273431777954,
  0.9479285478591919,
  0.9611882567405701,
  0.9626678824424744]}

In [28]:
# Recording history in json
import json
with open("training_hist.json","w") as f:
    json.dump(training_history.history,f)