In [1]:
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
import tensorflow as tf

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        print(e)


In [3]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


## Data Preprocessing
Preprocessed by ITBIN-2211-0233

Training Image Preprocessing

In [4]:
training_set = tf.keras.utils.image_dataset_from_directory(
    'train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 70295 files belonging to 38 classes.


Validation Image Preprocessing

In [5]:
validation_set = tf.keras.utils.image_dataset_from_directory(
    'valid',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 17572 files belonging to 38 classes.


In [6]:
training_set

<BatchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 38), dtype=tf.float32, name=None))>

In [7]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[148.5  143.5  147.5 ]
   [148.   143.   147.  ]
   [149.25 144.25 148.25]
   ...
   [139.   134.   138.  ]
   [137.5  132.5  136.5 ]
   [146.5  141.5  145.5 ]]

  [[149.5  144.5  148.5 ]
   [148.   143.   147.  ]
   [147.25 142.25 146.25]
   ...
   [157.75 152.75 156.75]
   [160.25 155.25 159.25]
   [151.5  146.5  150.5 ]]

  [[147.   142.   146.  ]
   [147.5  142.5  146.5 ]
   [149.25 144.25 148.25]
   ...
   [151.   146.   150.  ]
   [135.75 130.75 134.75]
   [146.5  141.5  145.5 ]]

  ...

  [[137.75 133.75 134.75]
   [139.   135.   136.  ]
   [136.25 132.25 133.25]
   ...
   [ 95.25  81.25  81.25]
   [ 93.    79.    79.  ]
   [ 98.25  84.25  84.25]]

  [[135.25 131.25 132.25]
   [132.5  128.5  129.5 ]
   [134.25 130.25 131.25]
   ...
   [ 98.    82.    83.  ]
   [101.25  85.25  86.25]
   [ 90.25  74.25  75.25]]

  [[140.25 136.25 137.25]
   [130.75 126.75 127.75]
   [130.25 126.25 127.25]
   ...
   [ 93.5   77.5   78.5 ]
   [ 96.    80.    81.  ]
   [ 95.25  79.25  8

Building Model

In [92]:

from keras.layers import Dense,Conv2D,MaxPool2D,Flatten,Dropout
from keras.models import Sequential



In [93]:
model = Sequential()

###  To avoid overshooting

1.Choose default learning rate as 0.0001

2.There may be chance of underfitting, so increase the number of neurons

3.Add more convolution layer to extrat more feature from images, there may be some posibility that model unable to capture relevent feature or model is confusing due to lack of feature. so feed with more feature.


## Building convalution Layer
BUILD BY ITBIN-2211-0256

In [94]:
model.add(Conv2D(filters=32,kernel_size=3,padding='same',activation='relu', input_shape=(128, 128, 3)))
model.add(Conv2D(filters=32,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [95]:
model.add(Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=64,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [96]:
model.add(Conv2D(filters=128,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=128,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [97]:
model.add(Conv2D(filters=256,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=256,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [99]:
model.add(Conv2D(filters=512,kernel_size=3,padding='same',activation='relu'))
model.add(Conv2D(filters=512,kernel_size=3,activation='relu'))
model.add(MaxPool2D(pool_size=2,strides=2))

In [100]:
model.add(Dropout(0.25)) # To avoid overfitting

In [101]:

model.add(Flatten())



In [103]:
model.add(Dense(units=1500,activation='relu'))

In [104]:
model.add(Dropout(0.4))

In [105]:
#Output layer
model.add(Dense(units=38,activation='softmax'))

Compiling Model

In [106]:
model.compile(optimizer=tf.keras.optimizers.Adam(
    learning_rate=0.0001),loss='categorical_crossentropy',metrics=['accuracy'])

In [107]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_53 (Conv2D)          (None, 128, 128, 32)      896       
                                                                 
 conv2d_54 (Conv2D)          (None, 126, 126, 32)      9248      
                                                                 
 max_pooling2d_30 (MaxPoolin  (None, 63, 63, 32)       0         
 g2D)                                                            
                                                                 
 conv2d_55 (Conv2D)          (None, 63, 63, 64)        18496     
                                                                 
 conv2d_56 (Conv2D)          (None, 61, 61, 64)        36928     
                                                                 
 max_pooling2d_31 (MaxPoolin  (None, 30, 30, 64)       0         
 g2D)                                                

## MODEL TRAINING 

Model Trained by ITBIN-2211-0258


In [108]:
training_history = model.fit(x=training_set,validation_data=validation_set,epochs=10)

Epoch 1/10
2197/2197 [==============================] - 131s 58ms/step - loss: 1.5461 - accuracy: 0.5464 - val_loss: 0.5906 - val_accuracy: 0.8185
Epoch 2/10
2197/2197 [==============================] - 129s 59ms/step - loss: 0.5004 - accuracy: 0.8417 - val_loss: 0.3619 - val_accuracy: 0.8885
Epoch 3/10
2197/2197 [==============================] - 128s 58ms/step - loss: 0.2988 - accuracy: 0.9042 - val_loss: 0.2086 - val_accuracy: 0.9321
Epoch 4/10
2197/2197 [==============================] - 129s 59ms/step - loss: 0.2097 - accuracy: 0.9318 - val_loss: 0.2251 - val_accuracy: 0.9276
Epoch 5/10
2197/2197 [==============================] - 127s 58ms/step - loss: 0.1483 - accuracy: 0.9518 - val_loss: 0.1515 - val_accuracy: 0.9516
Epoch 6/10
2197/2197 [==============================] - 129s 59ms/step - loss: 0.1141 - accuracy: 0.9636 - val_loss: 0.1855 - val_accuracy: 0.9414
Epoch 7/10
2197/2197 [==============================] - 130s 59ms/step - loss: 0.0976 - accuracy: 0.9683 - val_loss: 0